# Generated by Django 4.0.4 on 2023-01-18 18:59

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('department', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime(2023, 1, 18, 18, 59, 26, 258065, tzinfo=utc))),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2023, 1, 18, 18, 59, 26, 258357, tzinfo=utc))),
                ('semester', models.CharField(choices=[('fall', 'Fall'), ('spring', 'Spring')], max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('credits', models.IntegerField()),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='department.department')),
            ],
        ),
    ]
