# Generated by Django 4.0.4 on 2023-01-27 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_class', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentclass',
            name='year',
            field=models.CharField(max_length=10),
        ),
    ]
