# Generated by Django 4.0.4 on 2023-01-24 21:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('department', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('name', models.CharField(max_length=200)),
                ('gender', models.CharField(max_length=20)),
                ('dob', models.DateField()),
                ('email', models.CharField(max_length=200, unique=True)),
                ('address', models.CharField(max_length=200)),
                ('section', models.IntegerField()),
                ('joining_date', models.DateField()),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_students', to='department.department')),
            ],
        ),
    ]
